# Generated by Django 3.1.7 on 2021-04-17 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='Категория симптомов')),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=200, unique=True, verbose_name='Название класса заболеваний')),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom_text', models.CharField(max_length=500, unique=True, verbose_name='Симптом')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SDDDS.category', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.CharField(max_length=1000, verbose_name='Введённые симптомы')),
                ('result', models.CharField(max_length=1000, verbose_name='Рекомендованные специалисты')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=100, unique=True, verbose_name='Специалист')),
                ('allowing_diseases', models.ManyToManyField(blank=True, related_name='a_d', to='SDDDS.Disease', verbose_name='Лечит')),
            ],
        ),
        migrations.AddField(
            model_name='disease',
            name='allowing_symptoms',
            field=models.ManyToManyField(blank=True, related_name='a_s', to='SDDDS.Symptom', verbose_name='Возможные симптомы'),
        ),
        migrations.AddField(
            model_name='disease',
            name='prohibiting_symptoms',
            field=models.ManyToManyField(blank=True, related_name='p_s', to='SDDDS.Symptom', verbose_name='Исключающие симптомы'),
        ),
    ]
